exports.seed = async function (knex) {
  await knex("measureUnid").insert([
    { unid: "BALDE", description: "BALDE", valueIncrement: "1" },
    { unid: "BANDEJ", description: "BANDEJA", valueIncrement: "1" },
    { unid: "BARRA", description: "BARRA", valueIncrement: "1" },
    { unid: "BISNAG", description: "BISNAGA", valueIncrement: "1" },
    { unid: "CÁPSULAS", description: "CÁPSULA", valueIncrement: "1" },
    { unid: "CARRINHO", description: "CARTELA", valueIncrement: "1" },
    { unid: "CENTO", description: "CENTO", valueIncrement: "1" },
    { unid: "CX", description: "CAIXA", valueIncrement: "1" },
    { unid: "CX2", description: "CAIXA COM 2 UNIDADES", valueIncrement: "1" },
    { unid: "CX3", description: "CAIXA COM 3 UNIDADES", valueIncrement: "1" },
    { unid: "CX5", description: "CAIXA COM 5 UNIDADES", valueIncrement: "1" },
    { unid: "CX10", description: "CAIXA COM 10 UNIDADES", valueIncrement: "1" },
    { unid: "CX15", description: "CAIXA COM 15 UNIDADES", valueIncrement: "1" },
    { unid: "CX20", description: "CAIXA COM 20 UNIDADES", valueIncrement: "1" },
    { unid: "CX25", description: "CAIXA COM 25 UNIDADES", valueIncrement: "1" },
    { unid: "CX50", description: "CAIXA COM 50 UNIDADES", valueIncrement: "1" },
    {
      unid: "CX100",
      description: "CAIXA COM 100 UNIDADES",
      valueIncrement: "1",
    },
    { unid: "DISP", description: "EXIBIÇÃO", valueIncrement: "1" },
    { unid: "DUZIA", description: "DUZIA", valueIncrement: "0.5" },
    { unid: "FARDO", description: "FARDO", valueIncrement: "1" },
    { unid: "FOLHA", description: "FOLHA", valueIncrement: "1" },
    { unid: "FRASCO", description: "FRASCO", valueIncrement: "1" },
    { unid: "GALAO", description: "GALÃO", valueIncrement: "1" },
    { unid: "GF", description: "GARRAFA", valueIncrement: "1" },
    { unid: "GRAMAS", description: "GRAMAS", valueIncrement: "0.100" },
    { unid: "KG", description: "QUILOGRAMA", valueIncrement: "0.500" },
    { unid: "LATA", description: "LATA", valueIncrement: "1" },
    { unid: "LITRO", description: "LITRO", valueIncrement: "1" },
    { unid: "PACOTE", description: "PACOTE", valueIncrement: "1" },
    { unid: "PC", description: "PEÇA", valueIncrement: "1" },
    { unid: "ROLO", description: "ROLO", valueIncrement: "1" },
    { unid: "SACO", description: "SACO", valueIncrement: "1" },
    { unid: "SACOLA", description: "SACOLA", valueIncrement: "1" },
    { unid: "UNID", description: "UNIDADE", valueIncrement: "1" },
  ]);
};
